############################
# STAGE 1 execute Golang end to end integration tests
############################
FROM golang AS tester
ARG SLACKBOT_HELLO_URL
WORKDIR $GOPATH/src/github.com/buildit/slackbot
ADD . $GOPATH/src/github.com/buildit/slackbot/
RUN go get -d -v ./...
RUN go get -u github.com/jstemmer/go-junit-report
RUN mkdir /go/TestResults
RUN export SLACKBOT_HELLO_URL=${SLACKBOT_HELLO_URL}
RUN go test -v ./... -run E2E | go-junit-report > /go/TestResults/TestReport.xml 

############################
# STAGE 2 Upload test results to Azure
############################
FROM microsoft/dotnet:latest AS azcopier
ARG STORAGE_ACCT_URL
ARG STORAGE_ACCT_KEY
ARG BUILD_NUMBER
RUN apt-get update && apt-get -y install rsync --no-install-recommends apt-utils
RUN mkdir /tmp/azcopy && \
    wget -O /tmp/azcopy/azcopy.tar.gz https://aka.ms/downloadazcopyprlinux &&  \
    tar -xf /tmp/azcopy/azcopy.tar.gz -C /tmp/azcopy &&  \
    /tmp/azcopy/install.sh
RUN rm -rf /tmp/azcopy
COPY --from=tester /go/TestResults/TestReport.xml ./TestReport.xml
RUN azcopy \
     --source ./TestReport.xml \
     --destination "${STORAGE_ACCT_URL}/E2E_TestReport_${BUILD_NUMBER}.xml" \
     --dest-key "${STORAGE_ACCT_KEY}"