#!/bin/bash


# Set the default values for the parameter variables.
DEFAULT_CONTAINER_APP_NAME="RigContainerApp"
DEFAULT_CONTAINER_PLAN_NAME="RigContainerPlan"
DEFAULT_CONTAINER_REGISTRY_NAME="RigContainerRegistry"
DEFAULT_WEB_CONFIG_NAME="RigWebAppConfig"
DEFAULT_HOST_NAME_BINDING="rigcontainerapp.azurewebsites.net"
DEFAULT_APP_INSIGHTS_NAME="RigAppInsights"

DEFAULT_DATABASE_LOCATION_NAME="Central US"
DEFAULT_DATABASE_SERVER_NAME="***REMOVED***testservername"
DEFAULT_DATABASE_DB_NAME="testdatabase"
DEFAULT_DATABASE_ADMIN_USERNAME="azuresqladmin"
DEFAULT_DATABASE_ADMIN_PASSWORD="***REMOVED***"


# Read the parameter values from the command line.
echo
echo "Please fill in the config settings to store in your parameters.json"
echo "Defaults are shown in parenthesis.  <Enter> to accept."
echo

read -p "sites_RigContainerApp_name (\"$DEFAULT_CONTAINER_APP_NAME\"): " CONTAINER_APP_NAME
read -p "serverfarms_RigContainerPlan_name (\"$DEFAULT_CONTAINER_PLAN_NAME\"): " CONTAINER_PLAN_NAME
read -p "registries_RigContainerRegistry_name (\"$DEFAULT_CONTAINER_REGISTRY_NAME\"): " CONTAINER_REGISTRY_NAME
read -p "config_web_name (\"$DEFAULT_WEB_CONFIG_NAME\"): " WEB_CONFIG_NAME
read -p "hostNameBindings (\"$DEFAULT_HOST_NAME_BINDING\"): " HOST_NAME_BINDING
read -p "appInsightsName (\"$DEFAULT_APP_INSIGHTS_NAME\"): " APP_INSIGHTS_NAME

echo

read -p "location (\"$DEFAULT_DATABASE_LOCATION_NAME\"): " DATABASE_LOCATION_NAME
read -p "serverName (\"$DEFAULT_DATABASE_SERVER_NAME\"): " DATABASE_SERVER_NAME
read -p "databaseName (\"$DEFAULT_DATABASE_DB_NAME\"): " DATABASE_DB_NAME
read -p "administratorLogin (\"$DEFAULT_DATABASE_ADMIN_USERNAME\"): " DATABASE_ADMIN_USERNAME
read -p "administratorLoginPassword (\"$DEFAULT_DATABASE_ADMIN_PASSWORD\"): " DATABASE_ADMIN_PASSWORD
echo


# Assign the default values if the user didn't enter any value.
CONTAINER_APP_NAME="${CONTAINER_APP_NAME:-$DEFAULT_CONTAINER_APP_NAME}"
CONTAINER_PLAN_NAME="${CONTAINER_PLAN_NAME:-$DEFAULT_CONTAINER_PLAN_NAME}"
CONTAINER_REGISTRY_NAME="${CONTAINER_REGISTRY_NAME:-$DEFAULT_CONTAINER_REGISTRY_NAME}"
WEB_CONFIG_NAME="${WEB_CONFIG_NAME:-$DEFAULT_WEB_CONFIG_NAME}"
HOST_NAME_BINDING="${HOST_NAME_BINDING:-$DEFAULT_HOST_NAME_BINDING}"
APP_INSIGHTS_NAME="${APP_INSIGHTS_NAME:-$DEFAULT_APP_INSIGHTS_NAME}"

DATABASE_LOCATION_NAME="${DATABASE_LOCATION_NAME:-$DEFAULT_DATABASE_LOCATION_NAME}"
DATABASE_SERVER_NAME="${DATABASE_SERVER_NAME:-$DEFAULT_DATABASE_SERVER_NAME}"
DATABASE_DB_NAME="${DATABASE_DB_NAME:-$DEFAULT_DATABASE_DB_NAME}"
DATABASE_ADMIN_USERNAME="${DATABASE_ADMIN_USERNAME:-$DEFAULT_DATABASE_ADMIN_USERNAME}"
DATABASE_ADMIN_PASSWORD="${DATABASE_ADMIN_PASSWORD:-$DEFAULT_DATABASE_ADMIN_PASSWORD}"


# Build the parameters.json file using the above parameters.
PARAM_FILE="output/parameters.json"
cp templates/parameters.json $PARAM_FILE

sed -i '' "s/CONTAINER_APP_NAME/${CONTAINER_APP_NAME}/g" $PARAM_FILE
sed -i '' "s/CONTAINER_PLAN_NAME/${CONTAINER_PLAN_NAME}/g" $PARAM_FILE
sed -i '' "s/CONTAINER_REGISTRY_NAME/${CONTAINER_REGISTRY_NAME}/g" $PARAM_FILE
sed -i '' "s/WEB_CONFIG_NAME/${WEB_CONFIG_NAME}/g" $PARAM_FILE
sed -i '' "s/HOST_NAME_BINDING/${HOST_NAME_BINDING}/g" $PARAM_FILE
sed -i '' "s/APP_INSIGHTS_NAME/${APP_INSIGHTS_NAME}/g" $PARAM_FILE

sed -i '' "s/DATABASE_LOCATION_NAME/${DATABASE_LOCATION_NAME}/g" $PARAM_FILE
sed -i '' "s/DATABASE_SERVER_NAME/${DATABASE_SERVER_NAME}/g" $PARAM_FILE
sed -i '' "s/DATABASE_DB_NAME/${DATABASE_DB_NAME}/g" $PARAM_FILE
sed -i '' "s/DATABASE_ADMIN_USERNAME/${DATABASE_ADMIN_USERNAME}/g" $PARAM_FILE
sed -i '' "s/DATABASE_ADMIN_PASSWORD/${DATABASE_ADMIN_PASSWORD}/g" $PARAM_FILE


# Display an output message and end the script.
echo "Saved parameters.json!"
echo